### ISSUE TITLE
SimpleNLG for italian - static method processors or not?

### ISSUE THREAD

**Issue by CristinaBattaglino** [rali-udem/SimpleNLG-EnFr#5]
Hi,

we are working for creating the SimpleNLG extension for the italian language. We studied the SimpleNLG architecture and the SimpleNLGFrench modifications to the architecture. 
Is it better to implement the processors as classes that implement the NLGModule or to implement the processors as part of an NLG element (french approach). What are the disavantages of these two approaches?

**Comment by vaudrypl** [comment]
I'm posting the email that I sent concerning this post:

I'm happy to hear that you are working on an Italian extension of SimpleNLG. Like we mentioned in our ENLG 2013 paper, the purpose of making those methods non static was simply to make it possible to override them in the new subclasses. This way we could leave the most generic code in the superclass and put the French- and English-specific code in the respective subclasses. (Static methods cannot be overridden in subclasses in Java, just hidden. Hidden methods do not enable polymorphism.) The rules that must be applied to a specific unit can then selected on the fly depending on its language. A single document can thus contain French and English parts without problem.
