### ISSUE TITLE
Nombre spécifique

### ISSUE THREAD

**Issue by itoche** [rali-udem/SimpleNLG-EnFr#6]
Bonjour,

Comment peut-on définir un nombre précis pour un nom?

Par exemple:
Vous avez **deux** travaux supplémentaires

Merci

**Comment by itoche** [comment]
J'ai trouvé le moyen suivant:

NPPhraseSpec work = factory.createNounPhrase("le", "travail");
work.addModifier("supplémentaire");
work.addModifier("suivant");
**work.setSpecifier("deux");**

Est-ce correct?

**Comment by vaudrypl** [comment]
Désolé pour le délai de réponse, j'étais en vacances. Aucun mécanisme spécial n'est implémenté pour traiter les adjectifs cardinaux dans SimpleNLG-EnFr 1.1. Vous pouvez mettre un adjectif cardinal comme specifier, comme vous l'avez fait, mais le syntagme nominal ne sera pas mis automatiquement au pluriel. Pour cela, vous devez ajouter la ligne suivante :

work.setFeature(Feature.NUMBER, NumberAgreement.PLURAL);

**Comment by itoche** [comment]
Merci, c'est effectivement ce que j'ai fait.
